language: go
go:
  - 1.11.x

sudo: required

before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
  - cd ../.. &&
    mv coveo gruntwork-io &&
    cd gruntwork-io/terragrunt
  - wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

install:
  - make install

before_script:
  - if [ "${TRAVIS_TAG::1}" = "v" ]; then
      make full-test;
    else
      make test;
    fi
  - make fmtcheck

script:
  - if [ "${TRAVIS_TAG::1}" = "v" ]; then
      curl -sL https://git.io/goreleaser | bash;
    fi
  
after_success:
  - make coveralls


notifications:
  email: false
